CREATE TABLE CURRENCY (
  id INTEGER NOT NULL,
  symbol VARCHAR(7) NOT NULL,
  name  VARCHAR(31) NOT NULL
);

ALTER TABLE CURRENCY ADD CONSTRAINT PK_CURRENCY PRIMARY KEY (id);
ALTER TABLE CURRENCY ADD CONSTRAINT CURRENCY_UNQ_SYMBOL UNIQUE (symbol);