CREATE TABLE PRODUCT (
  id INTEGER NOT NULL,
  name  VARCHAR(31) NOT NULL,
  description VARCHAR(255) NOT NULL
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (id);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_UNQ_NAME UNIQUE (name);
