CREATE TABLE PRICE_POINT (
  id INTEGER NOT NULL,
  productid INTEGER NOT NULL,
  currencyid  INTEGER NOT NULL,
  productvalue NUMERIC NOT NULL
);

ALTER TABLE PRICE_POINT ADD CONSTRAINT PK_PRICE_POINT PRIMARY KEY (id);
ALTER TABLE PRICE_POINT ADD CONSTRAINT FK_PRICEPOINT_PROD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (ID);
ALTER TABLE PRICE_POINT ADD CONSTRAINT FK_PRICEPOINT_CUR FOREIGN KEY (CURRENCYID) REFERENCES CURRENCY (ID);
ALTER TABLE PRICE_POINT ADD CONSTRAINT PRICEPOINT_UNQ_PROD_CUR UNIQUE (productid, currencyid);

